### ISSUE TITLE
SOLID principles

### ISSUE THREAD

**Issue by Jecanart** [erik/Asteroids#1]
Hello!, as part of the software desing course in  the ESPOL College, our group was instructed to review github repositories and search for violations to the SOLID principles, as a result of this we found that your Asteroids project inflicts some violations to the SRP and OCP principles.

**SRP**
The SRP principle states that a module can only have one responsibility, but your class Stage has to control more things besides building the stage, it also controlls collitions and other processes as shown in the images bellow:
![image](https://user-images.githubusercontent.com/70679514/123444180-3a9e4f00-d59c-11eb-8519-abe8a83df863.png)
![image](https://user-images.githubusercontent.com/70679514/123444198-3f630300-d59c-11eb-9275-33b332d1b8f4.png)
![image](https://user-images.githubusercontent.com/70679514/123444212-42f68a00-d59c-11eb-98c3-fc6755f3d507.png)

The solution to this is to create diferent classes that controlls stage building, collitions, bounds checks and projectile movement, like the example bellow.
![image](https://user-images.githubusercontent.com/70679514/123444515-95d04180-d59c-11eb-8521-9e5a2edcb7fc.png)

**OCP**
The OCP principle states that a module has to be open to expansion and closed to modification, but in the Asteroid class if you want to add another size that is not one of the three already implemented, you would need to change all te constructors in the class to do so, a solution to this problem is to reemplace the class Asteroid with an interface and every size of the asteroid can implement the Asteroid interface, in this way if you want to add a new size you will only need to create a new class.
![image](https://user-images.githubusercontent.com/70679514/123445259-581fe880-d59d-11eb-99bb-0c7714ae8b7b.png)
![image](https://user-images.githubusercontent.com/70679514/123445271-5a824280-d59d-11eb-8d18-fdb7cfac9602.png)

**UML Graph**
![image](https://user-images.githubusercontent.com/70679514/123445326-67069b00-d59d-11eb-8e10-afc5f994cfb5.png)

Thats all, and thaks for letting us use you project.

**Comment by erik** [comment]
Hi John, appreciate the review!

You're absolutely right about the code organization being off here, this is a project I wrote in high school when I was first learning to build software. That said, since I haven't thought about this project in a decade, I won't be making any updates to the code.

Good luck with your course!
